# Generated by Django 5.0.4 on 2024-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_measurement_unit',
            field=models.CharField(choices=[('min', 'min'), ('ura', 'h'), ('dan', 'dan(a)')], default=False, max_length=7),
        ),
    ]
