# Generated by Django 3.2.12 on 2024-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='numberOfSuns',
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparationTimeMeasuringUnit',
            field=models.CharField(default='minutes', max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparationTimeNeeded',
            field=models.IntegerField(max_length=3),
        ),
    ]
