# Generated by Django 3.2.12 on 2024-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240423_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparationTimeNeeded',
            field=models.IntegerField(),
        ),
    ]
