# Generated by Django 5.0.4 on 2024-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_time_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_measurement_unit',
            field=models.CharField(choices=[('min', 'min'), ('ura', 'h'), ('dan', 'dan')], default=False, max_length=7),
        ),
    ]
