# Generated by Django 5.0.4 on 2024-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_time_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('piće', 'Piće'), ('hrana', 'Hrana'), ('lijek', 'Lijek')], default=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_measurement_unit',
            field=models.CharField(choices=[('min', 'min'), ('ura', 'h'), ('dan', 'dan')], default=False, max_length=8),
        ),
    ]
