# Generated by Django 3.2.12 on 2024-04-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_preparationtimeneeded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparationTimeMeasuringUnit',
            new_name='mjernaJecinicaPotrebnogVremenaPripreme',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='naziv',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='equipment',
            new_name='oprema',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparationTimeNeeded',
            new_name='potrebnoVrijemePripreme',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparationItself',
            new_name='priprema',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='sastojci',
        ),
    ]
