# Generated by Django 5.0.4 on 2024-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_category_alter_recipe_time_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='drink_subcategory',
            field=models.CharField(blank=True, choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('smoothie', 'Smoothie')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_subcategory',
            field=models.CharField(blank=True, choices=[('salad', 'Salad'), ('soup', 'Soup'), ('dessert', 'Dessert')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='medicine_subcategory',
            field=models.CharField(blank=True, choices=[('painkiller', 'Painkiller'), ('vitamin', 'Vitamin'), ('antibiotic', 'Antibiotic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('drink', 'Piće'), ('food', 'Hrana'), ('medicine', 'Lijek')], default=False, max_length=8),
        ),
    ]
