# Generated by Django 3.2.12 on 2024-04-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240424_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='naziv',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='naziv',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='oprema',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='sastojci',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='naziv',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='priprema',
            new_name='preperation',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='potrebnoVrijemePripreme',
            new_name='timeNeeded',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='mjernaJecinicaPotrebnogVremenaPripreme',
            new_name='timeNeededMeasuringUnit',
        ),
    ]
