# Generated by Django 3.2.12 on 2024-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240424_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='timeNeeded',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timeNeededMeasuringUnit',
            field=models.CharField(default='minuta', max_length=8),
        ),
    ]
