# Generated by Django 5.0.4 on 2024-04-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_drink_subcategory_recipe_food_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='drink_subcategory',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='food_subcategory',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='medicine_subcategory',
        ),
    ]
