# Generated by Django 5.0.4 on 2024-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_recipe_drink_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.TextField(default=False),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=False),
        ),
    ]
