# Generated by Django 5.0.4 on 2024-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recipe_equipment_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preperation',
            field=models.TextField(default=''),
        ),
    ]
