# Generated by Django 5.0.4 on 2024-05-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_recipe_preperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('food', 'Hrana'), ('drink', 'Piće'), ('medicine', 'Lijek')], default='food', max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_measurement_unit',
            field=models.CharField(choices=[('min', 'min'), ('ura', 'h'), ('dan', 'dan')], default='min', max_length=8),
        ),
    ]
