# Generated by Django 5.0.4 on 2024-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.IntegerField(default=1),
        ),
    ]
