# Generated by Django 5.0.4 on 2024-05-21 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_recipe_time_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
